# See <https://github.com/pyenv/pyenv/wiki#suggested-build-environment>.
- name: Install build dependencies for compiling Python versions
  apt:
    name:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    install_recommends: false
    state: present
  become: true

- name: Install pyenv
  shell: |
    if [ ! -d ~/.pyenv ]; then
      curl -sSL https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash

      if [ $? -ne 0 ]; then
        exit 1
      else
        echo status=changed
      fi
    fi
  args:
    executable: /bin/bash
  register: task
  changed_when: "'status=changed' in task.stdout"

- name: Add init code to `~/.profile`
  blockinfile:
    path: ~/.profile
    insertbefore: BOF
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: pyenv execs and shims"
    block: |
      # Add pyenv executable to PATH and enable shims
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"

- name: Add init code to `~/.bashrc`
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }} :: pyenv and venv load shell"
    block: |
      # Load pyenv into the shell
      eval "$(pyenv init -)"
      # Load pyenv-virtualenv automatically
      eval "$(pyenv virtualenv-init -)"

- name: Git checkout pyenv-virtualenv
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv
    dest: ~/.pyenv/plugins/pyenv-virtualenv

- name: Install Python {{ pyenv_global_python_version }} and enable it globally
  shell: |
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"

    pyenv global {{ pyenv_global_python_version }} || true

    if [ $(pyenv global) != {{ pyenv_global_python_version }} ]; then
      pyenv install {{ pyenv_global_python_version }}
      pyenv global {{ pyenv_global_python_version }}

      if [ $(pyenv global) != {{ pyenv_global_python_version }} ]; then
        exit 1
      else
        echo status=changed
      fi
    fi
  register: task
  changed_when: "'status=changed' in task.stdout"
